Algoritmo "EXERCICIO"

Var
A, B:logico
X, Y:real
R, S:caractere


Inicio
A <- Verdadeiro
B <- Falso
X <- 2.5
Y <- 5.0
R <- "Jose"
S <- "Joao"

escreval("O valor de A ou B é: ", A OU B)
escreval("O valor de A e B é: ", A e B)
escreval("O valor de Não A é: ", não A)
escreval("O valor de X = Y é: ", X = Y)
escreval("O valor de X = (Y/2) é: ", X = Y/2)
escreval("O valor de S = R é: ", S = R)
escreval("O valor de R != S é: ", S <> R)
escreval("O valor de R > S é: ", R > S)

Fimalgoritmo